apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  configmanagement.gke.io/cluster-selector: gke-prod-us-west2b-2

commonLabels:
  provider: gcp
  cluster: gke-prod-us-west2b-2