apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - ../../templates/service-db-redis.yaml

bases:
  - ./gke-prod
  - ./eks-prod
  - ./gke-prod-us-west2a-1
  - ./gke-prod-us-west2b-2
  - ./eks-prod-us-west2ab-1
  - ./eks-prod-us-west2ab-2
